bagaicha/urls.py
app_name = 'bagaicha'

import base64
import hashlib
import urllib
import uuid

import requests
from authlib.integrations.django_client import OAuth
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.urls import include, path
from django.views.generic.base import TemplateView

from .views import LoginWithView, RedirectUrlView, RefreshTokenView

urlpatterns = [
    path('', login_required(TemplateView.as_view(template_name='bagaicha.html'))),
    path('demo/', LoginWithView.as_view(), name='demo'),
    path('private/', RedirectUrlView.as_view(), name='private'),
    path('refresh/', RefreshTokenView.as_view(), name='refresh'),
]


# def generate_code_challenge():
#     #randomkey = str(uuid.uuid4())
#     randomkey = str("PredictableDemoCode")
#     return hashlib.sha256(randomkey.encode()).hexdigest()

# def oauth_client():
#     oauth=OAuth()
#     try:
#         oauth.register(
#             name='bagaicha',
#             client_id='2H7EwXHRy5YESvL8AkBVJtzGQVOgo3geu3DaWfWf',
#             client_secret='vQ8KAITx0HFu3CI496iQdAs8NzhvIdz94aWTkmBYVR77h52qiiLzsZrhH5nVE5BPd67vkYuptDRJk5W83tsjFekXrTCy908zdqCXbgLT7pRxPsT4l2QTX52YMISFbkvR',
#             access_token_url='http://dev.khalti.com.np:8004/o/token/',
#             access_token_params=None,
#             refresh_token_url=None,
#             authorize_url='http://dev.khalti.com.np:8004/o/authorize/',
#             client_kwargs=dict(code_challenge=generate_code_challenge(), code_challenge_method='S256', client_user_identifier='uid:109adfadsa'),
#         )
#     except Exception as exc:
#         raise

#     return oauth.bagaicha

kklogin/urls.py
from django.contrib import admin
from django.http import HttpResponse
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView, View
from django.contrib.auth.decorators import login_required

import oauth2_provider.views as oauth2_views

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('pass_reset/', auth_views.LoginView.as_view(), name='password_reset'),
]

urlpatterns += [
    path('bagaicha/', include('bagaicha.urls', namespace='bagaicha')),
        ]

urlpatterns += [
        path('',  RedirectView.as_view(url='bagaicha/'))
        ]

# OAuth2 provider endpoints
oauth2_endpoint_views = [
    path('authorize/', oauth2_views.AuthorizationView.as_view(), name="authorize"),
    path('token', oauth2_views.TokenView.as_view(), name="token"),
    path('revoke-token/', oauth2_views.RevokeTokenView.as_view(), name="revoke-token"),
]

    # OAuth2 Application Management endpoints
oauth2_endpoint_views += [
    path('applications/', login_required(oauth2_views.ApplicationList.as_view()), name="list"),
    path('applications/register/', login_required(oauth2_views.ApplicationRegistration.as_view()), name="register"),
    path('applications/<pk>/', login_required(oauth2_views.ApplicationDetail.as_view()), name="detail"),
    path('applications/<pk>/delete/', login_required(oauth2_views.ApplicationDelete.as_view()), name="delete"),
    path('applications/<pk>/update/', login_required(oauth2_views.ApplicationUpdate.as_view()), name="update"),
]

# OAuth2 Token Management endpoints
oauth2_endpoint_views += [
    path('authorized-tokens/', login_required(oauth2_views.AuthorizedTokensListView.as_view()), name="authorized-token-list"),
    path('authorized-tokens/<pk>/delete/', login_required(oauth2_views.AuthorizedTokenDeleteView.as_view()),
        name="authorized-token-delete"),
]

urlpatterns += [
    # OAuth 2 endpoints:
    path('o/', include((oauth2_endpoint_views, 'oauth2_provider'), namespace="oauth2_provider")),
]


from rest_framework import generics, permissions, serializers
from django.contrib.auth.models import User, Group
from oauth2_provider.contrib.rest_framework import TokenHasReadWriteScope, TokenHasScope
# first we define the serializers
class UserSerializer(serializers.ModelSerializer):
    class Meta:
        model = User
        fields = ('username', 'email', "first_name", "last_name")

class GroupSerializer(serializers.ModelSerializer):
    class Meta:
        model = Group
        fields = ("name", )

class UserList(View):
    # permission_classes = [permissions.IsAuthenticated, TokenHasReadWriteScope]
    def get(self, request):
        import json
        token_value = request.headers['Authorization'][7:]  # Bearer ****
        # token_value = request.META.get("HTTP_AUTHORIZATION")[7:]  # tong shang
        from oauth2_provider.models import get_access_token_model
        token = (
            get_access_token_model().objects.select_related("user", "application").get(token=token_value)
        )
        return HttpResponse(json.dumps({"name":token.user.username,"username":token.user.username, "email":token.user.email}))

class UserDetails(View):
    # permission_classes = [permissions.IsAuthenticated, TokenHasReadWriteScope]
    def get(self, request):
        import json
        return HttpResponse(json.dumps({"name":"test", "email":"test@test"}))

class GroupList(generics.ListAPIView):
    # permission_classes = [permissions.IsAuthenticated, TokenHasScope]
    required_scopes = ['groups']
    queryset = Group.objects.all()
    serializer_class = GroupSerializer

urlpatterns += [
    path('users/', UserList.as_view()),
    path('users/<pk>/', UserDetails.as_view()),
    path('users/emails', UserDetails.as_view()),
    path('groups/', GroupList.as_view()),
]

gatepass/models.py
from django.db import models

# Create your models here.

bagaicha/views.py
import base64
import hashlib
import urllib
import uuid
import json

import requests
from authlib.integrations.django_client import OAuth
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.urls import include, path
from django.views.generic.base import TemplateView

from gatepass.oauth.client import OAUTH_CLIENT_ID, OAUTH_ACCESS_TOKEN_URL, OAUTH_AUTHORIZE_URL, OAUTH_CLIENT_SECRET, OAUTH_REFRESH_TOKEN_URL
from gatepass.oauth.client import GatepassOAuthClient

# Create your views here.

gp_client =GatepassOAuthClient(
    client_id=OAUTH_CLIENT_ID,
    client_secret=OAUTH_CLIENT_SECRET
)

gp_client.configure(
    authorize_url=OAUTH_AUTHORIZE_URL,
    access_token_url=OAUTH_ACCESS_TOKEN_URL,
    refresh_token_url=OAUTH_REFRESH_TOKEN_URL,
    code_challenge=True,
    code_challenge_method='S256'
)

class LoginWithView(TemplateView):
    template_name='demo.html'

    def get_context_data(self, **kwargs):
        kw=super().get_context_data(**kwargs)

        redirect_url = 'http://g.uucin.com/login/generic_oauth'
        authorize_url = gp_client.generate_authorize_url(redirect_url)

        self.request.session['code_challenge'] = authorize_url.get('code_challenge')
        self.request.session['state'] = authorize_url.get('state')

        kw['authorize_url'] = authorize_url['url']
        print(kw['authorize_url'])
        kw['args'] = urllib.parse.urlparse(authorize_url['url']).query.split("&")
        kw['state'] = authorize_url['state']

        return kw

class RedirectUrlView(TemplateView):
    template_name='redirect.html'

    def get_context_data(self, **kwargs):
        kw = super().get_context_data(**kwargs)
        kw['get_args'] = self.request.GET

        # make access_Token_request
        # client=oauth_client()
        resp1={'code': self.request.GET.get('code'), 'state': self.request.GET.get('state')}

        code=self.request.GET.get('code')
        state=self.request.GET.get('state')

        code_challenge=self.request.session.get('code_challenge')

        redirect_url = self.request.build_absolute_uri('/login/generic_oauth')
        _response = gp_client.make_access_token_request(code=code, state=state, redirect_uri=redirect_url, code_challenge=code_challenge)

        response = json.loads(_response.text)
        kw['response'] = response

        kw['refresh_token'] = response.get('refresh_token')
        return kw

class RefreshTokenView(TemplateView):
    template_name='refresh.html'

    def get_context_data(self, **kwargs):
        kw = super().get_context_data(**kwargs)
        kw['get_args'] = self.request.GET

        # make access_Token_request
        # client=oauth_client()

        refresh_token=self.request.GET.get('token')

        redirect_url = self.request.build_absolute_uri('/login/generic_oauth')
        _response = gp_client.make_refresh_token_request(refresh_token)

        response = json.loads(_response.text)

        kw['response'] = response
        return kw

gatepass/views.py
from django.shortcuts import render

# Create your views here.

templates/bagaicha.html
{% extends 'base.html' %}
{% block content %}
<div style='padding:20px'>
<p>Welcome to Bagaicha.
</p>
<hr />
<p>
This is a sample OAuth2.0 implementation site - both as provider and consumer
</p>
<a href='{%url 'logout' %}'>Logout</a>

</div>
{% endblock %}

templates/base.html
<html>

<head>
    <title>{% block title %}Tim's Site{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
</head>

<body>
    <style>
        body {
            padding-top: 40px;
            padding-bottom: 40px;
            background-color: #f5f5f5;
        }
        
        #content {
            max-width: 700px;
            padding: 19px 29px 29px;
            margin: 0 auto 20px;
            background-color: #fff;
            border: 1px solid #e5e5e5;
            -webkit-border-radius: 5px;
            -moz-border-radius: 5px;
            border-radius: 5px;
            -webkit-box-shadow: 0 1px 2px rgba(0, 0, 0, .05);
            -moz-box-shadow: 0 1px 2px rgba(0, 0, 0, .05);
            box-shadow: 0 1px 2px rgba(0, 0, 0, .05);
        }
        
        .block-center .block-center-heading {
            margin-bottom: 10px;
        }
    </style>


    <div id="content" name="content" class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <a href="{%url 'oauth2_provider:list' %}">Applications</a>
                <a href="{%url 'oauth2_provider:authorized-token-list' %}">Tokens</a>
                <a href="{%url 'bagaicha:demo' %}">Demo client</a>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="jumbotron">
                    <h2>#Bagaicha</h2>
                </div>
                {% block content %} {% endblock %}


                <hr />
                <h3>
                    Login with Bagaicha (oauth impl)

                </h3>

                <pre>
1. Generate Login URL
{%url 'oauth2_provider:authorize'%}
</pre>



            </div>
        </div>
    </div>

</body>

</html>

templates/demo.html
{% extends 'base.html' %}
{%block content %}
<div style="margin:100px auto">
	<strong>authorization_url::</strong>
	<br />
	<code>
<ul>
	<li>
		Full URL <a href="{{authorize_url}}">{{authorize_url}}</a>
	</li>
{% for pcs in args %}
	<li>{{pcs}}</li>
{%endfor%}
</ul>
	</code>
	<br />

	<strong>state::</strong>
	<br />
	<code>
{{state}}
	</code>
	<hr />
<a href="{{authorize_url}}" class='btn btn-primary'>Login with Bagaicha</a>
</div>
{% endblock %}

templates/redirect.html
{% extends 'base.html' %} {%block content %}
<div style="margin:50px auto">
    <pre>
<strong>Data Received ::</strong>
	code={{request.GET.code}}
	state={{request.GET.state}}

<strong>Access Token Request::</strong>
url={{access_token_url}}
token={{access_token}}
response={{response}}
{{response.text}}
{{response.request.url}}
{{response.request.body}}
</pre>

    <a href="{%url 'bagaicha:refresh' %}?token={{refresh_token}}">Refresh This Token</a>
</div>

{% endblock %}

templates/refresh.html
{% extends 'base.html' %} {%block content %}
<div style="margin:50px auto">
    <strong>Refresh Token response::</strong>
    <br /> {{response}}

    <code>
    <strong>Previous Refresh Token </strong>
    <br />
    {{request.GET.token}}
    <br />
    <strong>New Issued Refresh Token</strong>
    <br />
    {{response.refresh_token}}
</code>


    <a href="{%url 'bagaicha:refresh' %}?token={{response.refresh_token}}">Refresh This Token</a>
</div>

{% endblock %}